### ISSUE TITLE
Add path for Wordpress theme?

### ISSUE THREAD

**Issue by v3nt** [RealFaviconGenerator/grunt-real-favicon#1]
Is there any way we can create or add the HTMLPrefix path to the Wordpress theme automatically? That's where my grunt file is...

**Comment by phbernard** [comment]
The plugin won't support PHP markups. That's too complex.

The workaround would be to place the markups in an external file (eg. `favicon_markups.html`) and include this file in `header.php` (eg. `include('favicon_markups.html')`).
