### ISSUE TITLE
Synchronize npm published versions

### ISSUE THREAD

**Issue by timkelty** [RealFaviconGenerator/grunt-real-favicon#11]
Versioning seems a little out of wack in this repo.

NPM has the latest published version as `0.0.4`, which matches `package.json`, but not what's in `master`.

Git tags would with versions would be nice.

It also seems to me that this should be published as 1.0.0, to be more aligned with `node-semver` standards: http://blog.npmjs.org/post/98131109725/npm-2-0-0?utm_source=nodeweekly&utm_medium=email

Would be nice, because I dig this project so much!

**Comment by phbernard** [comment]
mversion is now used in `grunt-real-favicon` and `rfg-api`. Much better, thank you for the tip!
