### ISSUE TITLE
No favicon.ico

### ISSUE THREAD

**Issue by wgasowski** [RealFaviconGenerator/grunt-real-favicon#14]
There is no favicon.ico inside directory with generated files.

Update: there is also no favicon-*.png files.

**Comment by luixxiul** [comment]
Is this not fixed yet, @phbernard ?

**Comment by phbernard** [comment]
For the "warning" part in the doc: Yep, that's done.

For the tests: nope, not yet. I'll go through the plugin TODO list in a week.

**Comment by phbernard** [comment]
Well, a week or two :-/

Done, `desktop_browser` section added to the first scenario.
