### ISSUE TITLE
[grunt] Enhance existing manifest.json when there's already one

### ISSUE THREAD

**Issue by nhoizey** [RealFaviconGenerator/grunt-real-favicon#21]
Currently, the grunt task is awesome for icons generation, but it replaces [my own Web App Manifest `manifest.json` file](https://github.com/nhoizey/esviji/blob/2c3122523d2c19abef26cbe7cb29df6a70b3c177/src/manifest.json) with the one generated.

I don't want to remove Real Favicon Generator from my grunt toolbox, so is it possible to either:
- add an option key in the Gruntfile to disable `manifest.json` generation
- or better, generate the same code, but appending it to the existing `manifest.json`

Thanks!

**Comment by phbernard** [comment]
Thank you!

It's already possible, use the [`existing_manifest` field in the `android_chrome` section](https://realfavicongenerator.net/api/non_interactive_api) (there's an example, look for "existing_manifest" in the page). You can also use the `on_conflict` setting to drive the behavior of the generator if one of your existing manifest field is to be overridden.

Note: when you inject your manifest in the request, escape it: it must be passed as a regular JSON string, not as a kind of sub-document.

**Comment by nhoizey** [comment]
So, if I keep my own manifest file, but without any `icons` key, setting `on_conflict: keep_existing` in my Gruntfile should do the job?

Also, time to move `existing_manifest` outside the `android_chrome` section… ;-)

**Comment by nhoizey** [comment]
Ok, no, it still overwrites my full existing manifest. So `on_conflict: keep_existing` only keeps keys that are in the `existing_manifest` data.

Any way to load my manifest file as an input for `existing_manifest`? I'm planning to automate part of its content (full name, short name, URL, etc.) before calling RFG.

**Comment by phbernard** [comment]
Not normal, what you suggest (`existing_manifest` + `on_conflict: keep_existing`) should work. There's an example in https://github.com/RealFaviconGenerator/realfavicongenerator-api-test-suite/blob/master/lib/android_chrome_test.rb, `test_existing_manifest` test case. Alright, that's ruby, but you get the spirit.

No, there is nothing right now in the Grunt plugin to load a file as the existing manifest, that should be done separately with a classic file read and a variable.

**Comment by nhoizey** [comment]
I didn't use `existing_manifest` because I wanted to keep my manifest **file** outside the `Gruntfile`.

I'll try to load the manifest file content…

**Comment by nhoizey** [comment]
And it works!

Just have to override file paths because of https://github.com/RealFaviconGenerator/realfavicongenerator/issues/207

**Comment by nhoizey** [comment]
I use these:
- https://github.com/nhoizey/esviji/blob/master/Gruntfile.js#L3
- https://github.com/nhoizey/esviji/blob/master/Gruntfile.js#L256-L257
- https://github.com/nhoizey/esviji/blob/master/Gruntfile.js#L288-L293

**Comment by phbernard** [comment]
Great! Perfect.

**Comment by nhoizey** [comment]
Wouldn't it be really better if it could enhance the existing manifest.json instead of requiring this kind of heavy Grunt configuration?
