### ISSUE TITLE
[grunt] use more generic name for icons in manifest.json

### ISSUE THREAD

**Issue by nhoizey** [RealFaviconGenerator/grunt-real-favicon#23]
The Web App Manifest `manifest.json` file is supposed to be supported in all browsers in the future (at least Chrome and Opera right now and Firefox soon), so icons names should be like `webapp-icon-144x144.png` instead of `android-chrome-144x144.png`.

**Comment by phbernard** [comment]
I'll regret the time when the manifest was only used by Android Chrome. I strongly believe RFG does the right thing by allowing to craft icons platform-per-platform. For some platforms, it's easily done (eg. iOS takes the Touch icons). For some, it's harder (eg. some IE take the larger PNG icon, whatever it is). In the "manifest.json is only for Android Chrome" era, the manifest was a bit like the Touch icon: a mechanism dedicated to a single platform. So far so good. Now, different platforms are going to pick whatever icon, based solely on its resolution. For example, both Android Chrome and Opera document a 48x48 icon.

There's an ongoing discussion here: http://discourse.wicg.io/t/making-icons-less-painful-and-murky/870

Alright, that will be another round of playing with various browsers to discover what each one is doing :) I've submitted https://github.com/RealFaviconGenerator/realfavicongenerator/issues/208

**Comment by nhoizey** [comment]
I like "all-unprecedented Super Retina 2 Turbo HD Tournament Edition Plus-Size screen resolution"… ;-)

I don't think we need to craft specific icons for each system. It's really a pain without RFG, and I believe RFG should not exist in an ideal world where standards rule browsers implementations… :-p
