### ISSUE TITLE
Preserve open graph image

### ISSUE THREAD

**Issue by nhoizey** [RealFaviconGenerator/grunt-real-favicon#24]
It seems the grunt task removes the open graph meta for image from my code.

Here is my source HTML:
https://github.com/nhoizey/esviji/blob/1f0d743ed0060ed50ce3a9f198211a52f72179cb/src/index.html#L13

The `<meta property="og:image" content="http://play.esviji.com/img/esviji-screenshot.png" />` disappears from the HTML when I use the RealFaviconGenerator grunt task.

The result is there: http://play.esviji.com/

**Comment by phbernard** [comment]
That's right. I entered https://github.com/RealFaviconGenerator/rfg-api/issues/4

**Comment by thib3113** [comment]
I resolve this for my personal use .

**Comment by phbernard** [comment]
`keep` option is available in grunt-real-favicon v0.2.3.

**Comment by nhoizey** [comment]
@phbernard thanks! Not sure my project will be updated any time, but it's nice seeing you still fix old issues.
