### ISSUE TITLE
Output to PHP file

### ISSUE THREAD

**Issue by superpoweredweb** [RealFaviconGenerator/grunt-real-favicon#25]
I set my gruntfile to output the icon paths to my header.php and it added a bit of "stuff" to my html and body tags, like this: `<?php="" body_class();="" ?="">>` Not sure how to make it not do that.

**Comment by skript-cc** [comment]
I encountered the same issue in a twig template. It happened to me both on the body tag and on another tag at the end of the template.

Currently my work around is to insert the tags in an empty template '_favicon_tags.twig' and include that in the head section of my template. This way the favicon generation isn't able to screw up the rest of my template.

**Comment by sdasilva03** [comment]
I'm doing the same thing for now. It would be nice to eliminate the extra copy/paste though.

**Comment by phbernard** [comment]
Thank you for reporting.

I don't understand how the Grunt plugin can inject these strange extra PHP markups. However, the plugin needs to parse the page where the markups should be added. Therefore, a PHP page can easily disrupt the parser, depending on how PHP markups are used.

So the "empty template" workaround suggested by @skript-cc sounds good to me.

**Comment by skript-cc** [comment]
@sdasilva03 No need for copy/paste. Just use `<?php include('favicons.html'); ?>` in your header.php file and point the grunt favicon task output to favicons.html.

**Comment by pire** [comment]
The same happens with EJS javascript templates. @skript-cc 's suggestion is a clever work-around for the time being! Thanks.

**Comment by phbernard** [comment]
I think we can safely close this one. The external, included markup file is the universal solution whatever the technology.
