### ISSUE TITLE
self.error is not a function

### ISSUE THREAD

**Issue by Pushplaybang** [RealFaviconGenerator/grunt-real-favicon#28]
Hey there I'm getting this

````
Running "real_favicon:create" (real_favicon) task
Fatal error: self.error is not a function
````

Any ideas where to start?

**Comment by phbernard** [comment]
How did you get this error? With the Gulp plugin? Grunt maybe?

**Comment by Pushplaybang** [comment]
grunt.  Hey there thanks, I was using grunt.

I managed to solve this, I think it may have been user error honestly, but after bumping into it refusing to output the favicon.ico, I've moved on, thanks though package served me well in the past.
