### ISSUE TITLE
Official extension for manifest file is .webmanifest, not .json

### ISSUE THREAD

**Issue by nhoizey** [RealFaviconGenerator/grunt-real-favicon#29]
This is now in the spec:
https://www.w3.org/TR/appmanifest/#media-type-registration

**Comment by phbernard** [comment]
I didn't realize this, thanks for reporting.

Hum... a new file extension and mime type... It will take years before all Web servers know the `.webmanifest` extension. And I can't imagine RFG asking to register the extension. So the question is: will browsers support the manifest when it doesn't have the valid content type (or no content type at all)?

I've just tested this on Ubuntu 14 LTS running Apache 2.4. No surprise: it doesn't know the `.webmanifest` extension, so the file is delivered without `Content-Type`. Android Chrome and Android Opera are smart (or careless? :) ) enough to process the file successfully anyway. 

I'm not sure about this one. It would surely make a good option (`.json` by default, `.webmanifest` if the user asks for it). But I feel like there are a lot of uncertainties right now, for both server and browser sides.

**Comment by nhoizey** [comment]
> a new file extension and mime type... It will take years before all Web servers know the .webmanifest extension.

True.

> I've just tested this on Ubuntu 14 LTS running Apache 2.4. No surprise: it doesn't know the .webmanifest extension, so the file is delivered without Content-Type.

I have anyway a few content-types in my `.htaccess` files because default ones in Apache are often not enough.

Do Apache 2.4 include the content-type for WOFF2, for example?

Maybe you could just add an option to define the target filename, and let the user decide if she wants to use a `.webmanifest` extension instead of the default `.json` one.

**Comment by nhoizey** [comment]
See also https://github.com/w3c/manifest/issues/346#issuecomment-89043694

**Comment by shoulders** [comment]
releated: 
https://github.com/RealFaviconGenerator/realfavicongenerator/issues/342
https://github.com/OneSignal/OneSignal-Website-SDK/issues/332
