### ISSUE TITLE
Globbing for Files Not Working

### ISSUE THREAD

**Issue by jcmcallister** [RealFaviconGenerator/grunt-real-favicon#30]
I'm not sure if I'm an idiot or if this is an actual problem.

In my Grunt workflow, after my `dist` folder is created, files are built and then copied into it, and my `index.html` file is created, I run the `realFavicons:favicons` task/target, with the following Grunt task config:

```javascript
module.exports = {
    favicons: {
        src: 'src/images/favicon-base.png',
        dest: 'dist/img/icons',
        options: {
            iconsPath: 'img/icons',
            html: ['dist/*.html'],
            design: { ...
```

If i use an explicit filename like "dist/index.html", it works and injects just fine, easy-peasy.

If I use the quasi-glob formula as shown above, the globbing does NOT work, and creates the file "*.html" with only the injected HTML code inside of it. This was an example on the "favicon result" page of realfavicongenerator.com .

For posterity, my global settings are in the attachment `Gruntfile.txt` which is loading all of my  grunt tasks. I am not the original author, and I'm not sure if the Gruntfile is disabling globbing (though I'm leaning towards a no).

[Gruntfile.txt](https://github.com/RealFaviconGenerator/grunt-real-favicon/files/394444/Gruntfile.txt)

Edited for formatting.

**Comment by phbernard** [comment]
Thank you for reporting!

I'm the idiot here. I've just release v0.1.7, which should fix the issue. Please let me know if that solves the problem on your side.

**Comment by jcmcallister** [comment]
I think you've got it!

The initial code example from the Issue works as expected with `html: ['dist/*.html'],`. 

**Please Note:** I have not done any more extensive testing due to other pressing work. Other such test cases should include `**/*.php` or other potential globbing patterns for common use cases.

Cheers, Philippe.
