### ISSUE TITLE
realFavicon task gives 301 Moved error

### ISSUE THREAD

**Issue by parkerwebteam** [RealFaviconGenerator/grunt-real-favicon#40]
I am getting the following error returned when I run the realFavicon grunt task...

`Fatal error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
...
301 Moved Permanently
...
The document has moved &lt;a href="https://realfavicongenerator.net/api/favicon"&gt;here</a&gt;

Apache/2.4.7 (Ubuntu) Server at realfavicongenerator.net Port 80
`

<br>
Ran an update: "grunt-real-favicon": "^0.1.7"

Tried updating http to https in the associated rfg-api module (rfg-api/index.js L50):
`client.post("http://realfavicongenerator.net/api/favicon", args, function(data, response) {`
but got error:
`Fatal error: Protocol "https:" not supported. Expected "http:"`

Any ideas welcome :)

**Comment by phbernard** [comment]
Fixed in Grunt plugin v0.2.1, released a minute ago. Thank you very much for having reported this one!

**Comment by parkerwebteam** [comment]
Thank you!

**Comment by marko-rbn** [comment]
I'm having same issue.  Updating various related packages didn't seem to help.  Can you please list commands that would help?
