### ISSUE TITLE
realFavicon task writes options html string into destination file

### ISSUE THREAD

**Issue by ThemePark** [RealFaviconGenerator/grunt-real-favicon#41]
In reference to closed issue: realFavicon task gives 301 Moved error #40

The v0.2.1 did indeed correct the previous error but appears to have introduced a new issue. The options: html path is being written into the beginning of the destination file as follows:

Note the first few characters of my _favicon-calls.html (html file saved as .txt for uploading)

[_favicon-calls.html.txt](https://github.com/RealFaviconGenerator/grunt-real-favicon/files/1243417/_favicon-calls.html.txt)

**Comment by phbernard** [comment]
v0.2.2 should be the one. Re-checked the instructions given by RFG, the output is now correct. Sorry for this unnecessary round trip...

**Comment by ThemePark** [comment]
Works as intended! Thanks for the rapid fix.
