### ISSUE TITLE
please fix npm audit vulnerabilities

### ISSUE THREAD

**Issue by axten** [RealFaviconGenerator/grunt-real-favicon#45]
npm reports the debug package to be unsafe:
<img width="570" alt="report" src="https://user-images.githubusercontent.com/1412778/49965755-5bdb4a80-ff1e-11e8-8903-b38f0424ae7d.png">

so maybe you can update the parent packages without problems

**Comment by phbernard** [comment]
Done in grunt-real-favicon v0.2.3.
