### ISSUE TITLE
Camel case properties

### ISSUE THREAD

**Issue by GaryJones** [RealFaviconGenerator/grunt-real-favicon#5]
The default within JS and Grunt / NodeJS is for variables and properties to use camel case, not underscores e.g. `pictureAspect` and not `picture_aspect`. Could this be switched over, or use aliases?

The use case is that code standards (JSCS) for a project can specify a check for not using underscored properties, so it's nice to get it consistent and not have to have exclusions for specific Grunt packages.

**Comment by phbernard** [comment]
Done, will be part of v0.1.0
