### ISSUE TITLE
Save the HTML

### ISSUE THREAD

**Issue by GaryJones** [RealFaviconGenerator/grunt-real-favicon#6]
It would be handy to have the option of saving the required HTML into a text file, so it can be manually inserted into wherever it is needed.

**Comment by pwolstenholme** [comment]
Or how about @taptapship /wiredep style injection of the HTML directly into our built HTML files through HTML comments like the below?
```html
<code>
<!-- grunt-real-favicon-->
<!-- endgrunt-real-favicon -->
</code>
```

**Comment by phbernard** [comment]
Done, this will be part of 0.1.0. I'm talking about dumping the HTML to a particular file, not about the comments you suggested, @philwolstenholme. If such feature would to be implemented, it would be part of the RFG's API, not the Grunt plugin.
