### ISSUE TITLE
Allow ios / windows: false

### ISSUE THREAD

**Issue by GaryJones** [RealFaviconGenerator/grunt-real-favicon#8]
Could the `ios` and `windows` properties accept a boolean false instead of an object, to indicate that none of the respective type of files should be generated?

**Comment by phbernard** [comment]
Sorry to report that late: this is now possible. Simply omits the corresponding section (`ios`, `windows`, etc.) and the corresponding icons and code won't be generated. This is documented in the <a href="http://realfavicongenerator.net/api/non_interactive_api">non-interactive API doc</a>.
